# main_vanilla_krum.py - Multi-Krum 防御 + BadNets 攻击
experiment_name: multikrum
logging:
  project: SafeFL_Vanilla
  use_wandb: true

model:
  name: resnet18
  params:
    num_classes: 10
    input_channels: 3

dataset: cifar10

algorithm:
  name: multi_krum
  params:
    screener:
      params:
        f: 4   # 预期的最大恶意客户端数量 (20 * 0.2 = 4)
        m: 14  # 最终选取的客户端数量 (通常 n - f - 2 = 20 - 4 - 2 = 14)

attack:
  enabled: true
