# @package _global_
training:
  num_clients: 100
  rounds: 150
  clients_fraction: 0.1
  lr_schedule:
    enabled: true
    name: warmup_cosine
    warmup_ratio: 0.1
    min_lr: 5.0e-5
    warmup_start_lr: 0.0

client:
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  optimizer_name: SGD
  criterion_name: CrossEntropyLoss
  epochs: 3
  batch_size: 64
  num_workers: 0
