from .fedavg import build_fedavg_algorithm
from .multi_krum import build_multi_krum_algorithm
from .flame import build_flame_algorithm
from .deepsight import build_deepsight_algorithm
from .fltrust import build_fltrust_algorithm
from .rflbat import build_rflbat_algorithm
from .foolsgold import build_foolsgold_algorithm
from .freqfed import build_freqfed_algorithm
from .mars import build_mars_algorithm
