# main_hfl.py - 异构联邦学习 (HFL) FoolsGold + FedRoLex
experiment_name: foolsgold_fedrolex
dataset: cifar10
epochs: 2
rounds: 150
device: cuda:2

logging:
  project: HFL_experiment1
  use_wandb: true

algorithm:
  name: foolsgold_fedrolex

attack:
  enabled: true
  malicious_epochs: 5

hetero:
  attacker:
    enabled: true
